"""Process isolation: cgroup v2 memory protection for inference processes.

LLM inference processes need special protection:
  1. OOM killer must NOT kill inference processes (memory.oom.group = 1)
  2. Memory must be reserved, not demand-paged (memory.min)
  3. NUMA affinity must be set for GPU-local memory
  4. CPU interference must be minimized (cpuset isolation)

This module generates systemd slice/scope configurations that protect
inference processes from being killed or degraded by other workloads.

Based on:
  - Blink (arxiv 2604.07609, April 2026): CPU interference causes 100x degradation
  - ghOSt scheduler: custom scheduling classes for AI
  - Linux cgroup v2: memory.min, memory.low, cpuset, io.weight
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass
class IsolationConfig:
    """cgroup v2 isolation configuration for an inference process."""
    name: str                        # Process/service name
    memory_min_gb: float = 0.0       # Guaranteed minimum RAM (memory.min)
    memory_max_gb: float = 0.0       # Hard limit (memory.max)
    memory_high_gb: float = 0.0      # Throttle threshold (memory.high)
    cpu_cores: list[int] | None = None  # Pinned CPU cores (cpuset.cpus)
    numa_node: int = -1              # NUMA node affinity
    io_weight: int = 100             # IO priority (1-10000, default 100)
    oom_score_adj: int = -900        # OOM killer priority (-1000 to 1000)
    nice: int = -10                  # Process nice value


def generate_systemd_slice(config: IsolationConfig) -> str:
    """Generate a systemd slice unit for inference process isolation.

    This creates a cgroup v2 slice that protects the inference process
    from being killed by the OOM killer and from CPU interference.
    """
    lines = [
        f"# AI OS inference isolation slice for {config.name}",
        "# Generated by aictl — protects inference from OOM and CPU interference",
        "[Unit]",
        f"Description=AI inference isolation for {config.name}",
        "Before=slices.target",
        "",
        "[Slice]",
    ]

    if config.memory_min_gb > 0:
        mem_min = int(config.memory_min_gb * 1024 * 1024 * 1024)
        lines.append(f"MemoryMin={mem_min}")

    if config.memory_max_gb > 0:
        mem_max = int(config.memory_max_gb * 1024 * 1024 * 1024)
        lines.append(f"MemoryMax={mem_max}")

    if config.memory_high_gb > 0:
        mem_high = int(config.memory_high_gb * 1024 * 1024 * 1024)
        lines.append(f"MemoryHigh={mem_high}")

    if config.cpu_cores:
        lines.append(f"AllowedCPUs={','.join(str(c) for c in config.cpu_cores)}")

    if config.io_weight != 100:
        lines.append(f"IOWeight={config.io_weight}")

    lines.extend([
        "",
        "# OOM protection: score -900 makes this nearly unkillable",
        f"OOMScoreAdjust={config.oom_score_adj}",
        "OOMPolicy=continue",
        "",
        "# CPU scheduling",
        f"Nice={config.nice}",
    ])

    if config.numa_node >= 0:
        lines.extend([
            "",
            "# NUMA affinity — bind to GPU-local memory node",
            f"# Apply with: numactl --cpunodebind={config.numa_node} --membind={config.numa_node}",
        ])

    return "\n".join(lines)


def generate_isolation_for_model(
    model_name: str,
    model_params_b: float,
    vram_gb: int = 0,
    ram_gb: int = 0,
) -> IsolationConfig:
    """Generate optimal isolation config for a model size."""
    # Estimate memory: 2 bytes/param (FP16) + 20% KV cache overhead
    # params_b is in billions, 1B params × 2 bytes = 2 GB
    model_ram_gb = model_params_b * 2 * 1.2

    if vram_gb > 0:
        # GPU mode: model is in VRAM, CPU needs less
        cpu_ram_gb = max(4.0, model_ram_gb * 0.1)  # 10% for CPU-side buffers
    else:
        # CPU mode: model is fully in RAM
        cpu_ram_gb = model_ram_gb

    config = IsolationConfig(
        name=model_name.replace("/", "-").replace(":", "-"),
        memory_min_gb=round(cpu_ram_gb, 1),
        memory_max_gb=round(cpu_ram_gb * 2, 1),
        memory_high_gb=round(cpu_ram_gb * 1.5, 1),
        oom_score_adj=-900,
        nice=-10,
        io_weight=200,  # Higher than default for model loading
    )

    return config


def detect_cpu_isolation_support() -> dict[str, bool]:
    """Check what CPU isolation features are available."""
    from pathlib import Path

    return {
        "cgroup_v2": Path("/sys/fs/cgroup/cgroup.controllers").exists(),
        "cpuset": Path("/sys/fs/cgroup/cpuset.cpus.effective").exists(),
        "memory_min": Path("/sys/fs/cgroup/memory.min").exists(),
        "numa": Path("/sys/devices/system/node/node0").exists(),
        "isolcpus": "isolcpus" in Path("/proc/cmdline").read_text()
                    if Path("/proc/cmdline").exists() else False,
    }
