#!/usr/bin/env bash
# AI Native Linux OS — One-line installer
# curl -sSL https://raw.githubusercontent.com/shizukutanaka/aios/main/scripts/install.sh | bash
set -euo pipefail

REPO="${AIOS_REPO:-https://github.com/shizukutanaka/aios}"
INSTALL_DIR="${AIOS_INSTALL_DIR:-/opt/aios}"
BIN_LINK="${AIOS_BIN_LINK:-/usr/local/bin/aictl}"

# Only escalate when we actually need to. Running as root, or installing
# somewhere the user already owns, needs no sudo — and requiring it broke the
# update path below, where `git pull` ran unprivileged against a root-owned
# clone and killed the script via `set -e`.
SUDO=""
if [ "$(id -u)" -ne 0 ]; then
    SUDO="sudo"
fi

info()  { echo -e "\033[0;32m✓\033[0m $*"; }
warn()  { echo -e "\033[0;33m⚠\033[0m $*"; }
err()   { echo -e "\033[0;31m✗\033[0m $*"; exit 1; }

# Find an interpreter new enough to run aictl, newest first.
# Compares the version as a pair, not as two independent numbers: the old
# `[ "$major" -ge 3 ] && [ "$minor" -ge 11 ]` rejects a hypothetical 4.0
# because 0 is not >= 11.
detect_python() {
    local p ver major minor
    for p in python3.13 python3.12 python3.11 python3; do
        command -v "$p" >/dev/null 2>&1 || continue
        ver=$("$p" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null) || continue
        major="${ver%%.*}"
        minor="${ver##*.}"
        if [ "$major" -gt 3 ] || { [ "$major" -eq 3 ] && [ "$minor" -ge 11 ]; }; then
            command -v "$p"
            return 0
        fi
    done
    return 1
}

# Write the `aictl` wrapper, pinned to the interpreter we verified.
#
# This used to be a quoted heredoc ending in `exec python3 -m aictl "$@"`,
# which threw away the entire point of detect_python: on a machine where
# `python3` is 3.9 and `python3.11` is installed, the installer printed
# "Python: python3.11" and then wrote a wrapper that ran 3.9. The check passed,
# the install reported success, and aictl was broken on first use.
write_wrapper() {
    local python_path="$1" target="$2" install_dir="$3"
    $SUDO tee "$target" > /dev/null <<WRAPPER
#!/bin/bash
# Generated by scripts/install.sh — pinned to the interpreter verified at
# install time. Do not replace with a bare \`python3\`: that is not necessarily
# the same interpreter, and may be too old to run aictl.
export PYTHONPATH=${install_dir}:\${PYTHONPATH:-}
exec ${python_path} -m aictl "\$@"
WRAPPER
    $SUDO chmod +x "$target"
}

main() {
    echo
    echo "  AI Native Linux OS — Installer"
    echo "  ================================"
    echo

    local PYTHON
    if ! PYTHON=$(detect_python); then
        err "Python 3.11+ required. Install: sudo dnf install python3 (or apt install python3)"
    fi
    info "Python: $PYTHON ($("$PYTHON" --version 2>&1))"

    local USE_GIT=true
    if ! command -v git >/dev/null 2>&1; then
        warn "git not found — installing from tarball instead"
        USE_GIT=false
    fi

    if [ "$USE_GIT" = true ]; then
        if [ -d "$INSTALL_DIR/.git" ]; then
            info "Updating existing installation..."
            $SUDO git -C "$INSTALL_DIR" pull --quiet
        else
            info "Cloning repository..."
            $SUDO git clone --depth 1 "$REPO.git" "$INSTALL_DIR"
        fi
    else
        info "Downloading release..."
        local TMP
        TMP=$(mktemp -d)
        curl -sSL "$REPO/archive/refs/heads/main.tar.gz" | tar xz -C "$TMP"
        $SUDO mkdir -p "$INSTALL_DIR"
        $SUDO cp -r "$TMP"/aios-main/* "$INSTALL_DIR/"
        rm -rf "$TMP"
    fi

    write_wrapper "$PYTHON" "$BIN_LINK" "$INSTALL_DIR"
    info "Installed: $BIN_LINK"

    # Verify the file we just wrote, by path. Calling plain `aictl` here tests
    # whatever PATH resolves first — which may be an older install, or nothing
    # at all if /usr/local/bin is not on PATH.
    if "$BIN_LINK" --help >/dev/null 2>&1; then
        info "Installation verified"
    else
        warn "Installation completed but $BIN_LINK --help failed"
    fi

    if ! command -v aictl >/dev/null 2>&1; then
        warn "$(dirname "$BIN_LINK") is not on your PATH — add it to use \`aictl\` directly"
    fi

    echo
    echo "  Post-install:"

    if command -v podman >/dev/null 2>&1; then
        info "Podman: $(podman --version 2>/dev/null | head -1)"
    else
        warn "Podman not found — install: sudo dnf install podman"
    fi

    if command -v nvidia-smi >/dev/null 2>&1; then
        info "NVIDIA GPU: $(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1)"
    else
        echo "  · No NVIDIA GPU detected (CPU-only mode)"
    fi

    if command -v ollama >/dev/null 2>&1; then
        info "Ollama: $(ollama --version 2>/dev/null)"
    else
        echo "  · Ollama not found — install: curl -fsSL https://ollama.com/install.sh | sh"
    fi

    echo
    echo "  Quick start:"
    echo "    aictl init"
    echo "    aictl doctor"
    echo "    aictl recipe run local-chat"
    echo
}

# Tests source this file to exercise detect_python/write_wrapper directly.
# Anything else — including `curl | bash`, where BASH_SOURCE is unreliable —
# installs as before.
if [ "${AIOS_INSTALL_LIB:-}" != "1" ]; then
    main "$@"
fi
